services:
    backendapp:
        container_name: backendapp
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "9000:9000"
        volumes:
            - ./backendapp:/app:delegated
        networks:
            - network
        # env_file:
        #     - .docker.env
    nginx:
        container_name: nginx
        image: nginx:1.17.3-alpine
        command: sh -c "chmod 777 -Rc /app/storage && chmod 777 -Rc /app/bootstrap/cache && nginx -g \"daemon off;\""
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./backendapp:/app:delegated
            - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - backendapp
        networks:
            - network
volumes:
    backendapp:
    nginx:
networks:
    network:
        driver: bridge
